export const RECIPES_DEFAULT = [
  {
    id: 1,
    nom: "Soupe ramen au bœuf",
    description: "Un ramen réconfortant avec bouillon profond, patate douce et gingembre frais.",
    categorie: "soupe",
    proteine: "boeuf",
    saison: "hiver",
    prepMin: 15,
    cuissonMin: 30,
    portions: 2,
    statut: "À essayer",
    etoiles: 0,
    tags: ["asiatique", "comfort food", "gingembre", "épicé"],
    ingredients: [
      "300g de bœuf tranché finement",
      "2 portions de nouilles ramen",
      "1 patate douce en rondelles",
      "4 tasses de bouillon de bœuf",
      "2 cm de gingembre frais râpé",
      "2 c. à soupe de sauce soya",
      "1 lime",
      "2 œufs mollets",
      "Oignons verts pour garnir",
    ],
    etapes: [
      "Porter le bouillon à ébullition avec le gingembre et la sauce soya.",
      "Ajouter la patate douce et cuire 10 min à feu moyen.",
      "Saisir le bœuf dans une poêle chaude, 2–3 min.",
      "Cuire les nouilles ramen selon les instructions, égoutter.",
      "Assembler les bols : nouilles, bouillon chaud, bœuf et patate douce.",
      "Garnir d'un œuf mollet, oignons verts et filet de lime.",
    ],
    notes: "Recette inspirée d'un Reel Instagram. Essayer avec du miso pour plus de profondeur.",
    source: "Instagram @chefjulie_cuisine",
  },
  {
    id: 2,
    nom: "Poulet rôti citron & herbes",
    description: "Un classique indémodable — cuisses dorées, herbes fraîches et zeste de citron.",
    categorie: "souper",
    proteine: "poulet",
    saison: "toutes saisons",
    prepMin: 10,
    cuissonMin: 40,
    portions: 4,
    statut: "Approuvée",
    etoiles: 4,
    tags: ["citron", "santé", "herbes", "four"],
    ingredients: [
      "4 cuisses de poulet avec os",
      "2 citrons (zeste et jus)",
      "4 gousses d'ail écrasées",
      "3 c. à soupe d'huile d'olive",
      "1 c. à thé de thym séché",
      "1 c. à thé de romarin",
      "Sel et poivre",
    ],
    etapes: [
      "Préchauffer le four à 200°C.",
      "Mélanger huile, zeste de citron, jus, ail et herbes.",
      "Enrober le poulet de marinade, saler et poivrer.",
      "Déposer dans un plat allant au four.",
      "Cuire 35–40 min jusqu'à dorure et cuisson complète.",
      "Laisser reposer 5 min avant de servir.",
    ],
    notes: "Excellent avec des légumes rôtis au même four. Doubler la marinade pour plus de saveur.",
    source: "Recette familiale",
  },
  {
    id: 3,
    nom: "Saumon teriyaki & riz jasmin",
    description: "Un souper rapide et élégant — saumon laqué sur riz jasmin parfumé.",
    categorie: "souper",
    proteine: "poisson",
    saison: "toutes saisons",
    prepMin: 10,
    cuissonMin: 15,
    portions: 2,
    statut: "Favorite",
    etoiles: 5,
    tags: ["asiatique", "rapide", "santé", "umami"],
    ingredients: [
      "2 filets de saumon",
      "3 c. à soupe de sauce soya",
      "2 c. à soupe de miel",
      "1 c. à soupe de mirin",
      "1 gousse d'ail râpée",
      "1 cm de gingembre râpé",
      "1 tasse de riz jasmin",
      "Graines de sésame et oignons verts",
    ],
    etapes: [
      "Mélanger sauce soya, miel, mirin, ail et gingembre pour la sauce teriyaki.",
      "Mariner le saumon 15–30 min au réfrigérateur.",
      "Cuire le riz jasmin selon les instructions.",
      "Chauffer une poêle à feu moyen-vif avec un peu d'huile.",
      "Saisir le saumon 3–4 min par côté en nappant de sauce.",
      "Servir sur riz avec sésame et oignons verts.",
    ],
    notes: "La recette préférée de toute la famille. Ne pas trop cuire le saumon.",
    source: "Adaptation maison",
  },
  {
    id: 4,
    nom: "Buddha bowl au tofu croustillant",
    description: "Un bol coloré et nourrissant — tofu doré, légumes de saison, sauce tahini-citron.",
    categorie: "déjeuner",
    proteine: "tofu",
    saison: "printemps",
    prepMin: 20,
    cuissonMin: 25,
    portions: 2,
    statut: "Testée",
    etoiles: 3,
    tags: ["végétalien", "santé", "léger", "coloré"],
    ingredients: [
      "300g de tofu ferme en cubes",
      "1 tasse de quinoa",
      "1 avocat tranché",
      "1 betterave râpée",
      "1 tasse de chou mauve tranché",
      "2 c. à soupe de tahini",
      "Jus d'1 citron",
      "1 c. à soupe d'huile de sésame",
      "2 c. à soupe de sauce soya",
    ],
    etapes: [
      "Presser le tofu pour enlever l'excès d'eau, couper en cubes.",
      "Faire revenir le tofu avec sauce soya et huile de sésame jusqu'à dorure.",
      "Cuire le quinoa selon les instructions.",
      "Préparer la sauce : tahini + citron + 2 c. à soupe d'eau.",
      "Assembler : quinoa, tofu, légumes variés.",
      "Napper de sauce tahini et servir immédiatement.",
    ],
    notes: "Essayer le tofu au four (200°C, 25 min) pour plus de croustillant.",
    source: "Magazine Saveurs",
  },
  {
    id: 5,
    nom: "Tarte tatin aux pommes",
    description: "La classique française — pommes caramélisées et pâte feuilletée dorée.",
    categorie: "dessert",
    proteine: "végétarien",
    saison: "automne",
    prepMin: 20,
    cuissonMin: 45,
    portions: 6,
    statut: "Approuvée",
    etoiles: 4,
    tags: ["comfort food", "français", "sucré", "automne"],
    ingredients: [
      "6 pommes Golden ou Cortland",
      "100g de beurre",
      "150g de sucre",
      "1 rouleau de pâte feuilletée",
      "1 c. à thé de cannelle",
      "Crème fraîche pour servir",
    ],
    etapes: [
      "Préchauffer le four à 190°C.",
      "Éplucher et couper les pommes en quartiers.",
      "Faire un caramel avec beurre et sucre dans une poêle allant au four.",
      "Disposer les pommes en rosace dans le caramel chaud.",
      "Cuire à feu moyen 10 min jusqu'à caramélisation.",
      "Couvrir de pâte feuilletée en rentrant les bords.",
      "Enfourner 25–30 min jusqu'à dorure.",
      "Démouler immédiatement et servir tiède.",
    ],
    notes: "La clé : bien caraméliser les pommes. Les Cortland tiennent mieux à la cuisson.",
    source: "Recette de grand-maman",
  },
];
